[2024-06-28T10:14:51.552+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T10:14:51.579+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_data.download_stock_data manual__2024-06-28T10:13:51.802131+00:00 [queued]>
[2024-06-28T10:14:51.586+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_data.download_stock_data manual__2024-06-28T10:13:51.802131+00:00 [queued]>
[2024-06-28T10:14:51.587+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T10:14:51.608+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_stock_data> on 2024-06-28 10:13:51.802131+00:00
[2024-06-28T10:14:51.622+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=44) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T10:14:51.625+0000] {standard_task_runner.py:63} INFO - Started process 49 to run task
[2024-06-28T10:14:51.631+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'download_data', 'download_stock_data', 'manual__2024-06-28T10:13:51.802131+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/download_data.py', '--cfg-path', '/tmp/tmpuj1wwni3']
[2024-06-28T10:14:51.635+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask download_stock_data
[2024-06-28T10:14:51.648+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-28T10:14:51.700+0000] {task_command.py:426} INFO - Running <TaskInstance: download_data.download_stock_data manual__2024-06-28T10:13:51.802131+00:00 [running]> on host 0d0315ca3a10
[2024-06-28T10:14:51.782+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_data' AIRFLOW_CTX_TASK_ID='download_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T10:13:51.802131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T10:13:51.802131+00:00'
[2024-06-28T10:14:51.784+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T10:14:51.815+0000] {download_data.py:18} INFO - Starting data download for AAPL for period 1y
[2024-06-28T10:14:51.815+0000] {logging_mixin.py:188} INFO - yfinance: pandas_datareader support is deprecated & semi-broken so will be removed in a future verison. Just use yfinance.
[2024-06-28T10:14:51.820+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-06-28T10:15:03.631+0000] {base.py:126} ERROR - Failed to get ticker 'AAPL' reason: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/AAPL?range=1d&interval=1d&crumb=Rev%2Fb2GdkLk (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff66583740>: Failed to resolve 'query2.finance.yahoo.com' ([Errno -3] Temporary failure in name resolution)"))
[2024-06-28T10:15:06.096+0000] {logging_mixin.py:188} WARNING - [*********************100%%**********************]  1 of 1 completed
[2024-06-28T10:15:06.110+0000] {download_data.py:21} INFO - Data download complete, number of rows downloaded: 252
[2024-06-28T10:15:06.153+0000] {download_data.py:23} INFO - Data saved to /opt/***/data/data.csv
[2024-06-28T10:15:06.159+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T10:15:06.166+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T10:15:06.267+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=download_data, task_id=download_stock_data, run_id=manual__2024-06-28T10:13:51.802131+00:00, execution_date=20240628T101351, start_date=20240628T101451, end_date=20240628T101506
[2024-06-28T10:15:06.384+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T10:15:06.459+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T10:15:06.463+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
