[2024-06-27T16:22:05.534+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T16:22:05.551+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_data.wait_for_download manual__2024-06-27T16:22:03.347365+00:00 [queued]>
[2024-06-27T16:22:05.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_data.wait_for_download manual__2024-06-27T16:22:03.347365+00:00 [queued]>
[2024-06-27T16:22:05.555+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T16:22:05.561+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_download> on 2024-06-27 16:22:03.347365+00:00
[2024-06-27T16:22:05.569+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=48) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T16:22:05.570+0000] {standard_task_runner.py:63} INFO - Started process 54 to run task
[2024-06-27T16:22:05.571+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_data', 'wait_for_download', 'manual__2024-06-27T16:22:03.347365+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_data.py', '--cfg-path', '/tmp/tmpwa57cf5g']
[2024-06-27T16:22:05.573+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask wait_for_download
[2024-06-27T16:22:05.583+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-27T16:22:05.607+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocess_data.wait_for_download manual__2024-06-27T16:22:03.347365+00:00 [running]> on host dc4243757e06
[2024-06-27T16:22:05.665+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_data' AIRFLOW_CTX_TASK_ID='wait_for_download' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T16:22:03.347365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T16:22:03.347365+00:00'
[2024-06-27T16:22:05.665+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T16:22:05.673+0000] {baseoperator.py:400} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-06-27T16:22:05.673+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:22:05.674+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-06-27T16:23:06.593+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:24:16.282+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:25:16.366+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:26:16.431+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:27:16.505+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:28:16.799+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:29:23.231+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:30:23.431+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:31:23.536+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:32:23.632+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:22:03.347365+00:00 ... 
[2024-06-27T16:32:23.745+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T16:32:23.851+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 618.0254504499999 seconds exceeds the specified timeout of 600.0.
[2024-06-27T16:32:24.152+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=preprocess_data, task_id=wait_for_download, run_id=manual__2024-06-27T16:22:03.347365+00:00, execution_date=20240627T162203, start_date=20240627T162205, end_date=20240627T163224
[2024-06-27T16:32:24.319+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task wait_for_download (Sensor has timed out; run duration of 618.0254504499999 seconds exceeds the specified timeout of 600.0.; 54)
[2024-06-27T16:32:24.474+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T16:32:24.905+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T16:32:24.913+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
