[2024-06-27T16:05:56.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T16:05:56.384+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_data.wait_for_download manual__2024-06-27T16:05:52.432449+00:00 [queued]>
[2024-06-27T16:05:56.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_data.wait_for_download manual__2024-06-27T16:05:52.432449+00:00 [queued]>
[2024-06-27T16:05:56.390+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T16:05:56.401+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_download> on 2024-06-27 16:05:52.432449+00:00
[2024-06-27T16:05:56.412+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=48) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T16:05:56.414+0000] {standard_task_runner.py:63} INFO - Started process 54 to run task
[2024-06-27T16:05:56.415+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_data', 'wait_for_download', 'manual__2024-06-27T16:05:52.432449+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_data.py', '--cfg-path', '/tmp/tmpzoy0wmxa']
[2024-06-27T16:05:56.418+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask wait_for_download
[2024-06-27T16:05:56.429+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-27T16:05:56.455+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocess_data.wait_for_download manual__2024-06-27T16:05:52.432449+00:00 [running]> on host e1bac596bd02
[2024-06-27T16:05:56.519+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_data' AIRFLOW_CTX_TASK_ID='wait_for_download' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T16:05:52.432449+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T16:05:52.432449+00:00'
[2024-06-27T16:05:56.520+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T16:05:56.532+0000] {baseoperator.py:400} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-06-27T16:05:56.533+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:05:56.533+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-06-27T16:06:56.551+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:07:56.623+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:08:56.667+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:09:56.736+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:10:56.790+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:11:56.825+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:12:56.895+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:13:56.950+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:14:57.005+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:15:57.048+0000] {external_task.py:258} INFO - Poking for tasks ['download_stock_data'] in dag download_data on 2024-06-27T16:05:52.432449+00:00 ... 
[2024-06-27T16:15:57.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T16:15:57.111+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.6058143569999 seconds exceeds the specified timeout of 600.0.
[2024-06-27T16:15:57.132+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=preprocess_data, task_id=wait_for_download, run_id=manual__2024-06-27T16:05:52.432449+00:00, execution_date=20240627T160552, start_date=20240627T160556, end_date=20240627T161557
[2024-06-27T16:15:57.159+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task wait_for_download (Sensor has timed out; run duration of 600.6058143569999 seconds exceeds the specified timeout of 600.0.; 54)
[2024-06-27T16:15:57.207+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T16:15:57.259+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T16:15:57.263+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
